"""add seats_billed to billing_orders

Revision ID: 97fcdbf7ed11
Revises: bc0ace015620
Create Date: 2026-09-26 15:19:37.987297

"""
from alembic import op
import sqlalchemy as sa



revision = '97fcdbf7ed11'
down_revision = 'bc0ace015620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_orders', sa.Column('seats_billed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_orders', 'seats_billed')
    # ### end Alembic commands ###
