"""client personalization fields, deal order+product, message channels

Revision ID: e571437e56e5
Revises: 97fcdbf7ed11
Create Date: 2026-09-26 21:27:18.660190

"""
from alembic import op
import sqlalchemy as sa



revision = 'e571437e56e5'
down_revision = '97fcdbf7ed11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('first_name', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('last_name', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('telegram_chat_id', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('viber_id', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('order_number', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('product_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'product_summary')
    op.drop_column('deals', 'order_number')
    op.drop_column('clients', 'viber_id')
    op.drop_column('clients', 'telegram_chat_id')
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')
    # ### end Alembic commands ###
